### PR TITLE
Added fill on layoutSizingHorizontal to column auto layout

### PR DESCRIPTION
**Pull request by mrksoftware**
When you create a table starting from a cell component, the result is not responsive when resized to fill the horizontal space. This is due to the fact that the column auto layout has layoutSizingHorizontal set to 'hug'

Here an example with the old version:
table-builder-old

Here is an example with the new version:
table-builder-new

In the new version, I've changed the layoutSizingHorizontal to 'Fill' and set the table minWidth to the cell's width multiplied for the number of columns inserted by the user, so that the resulting table will have the perfect size to contain all the new cells

### CODE REVIEW

**Comment by NatashaDudi** [comment]
Hello @mrksoftware, thank you for your suggestions. Since the table builder plugin is mainly used to have columns in various width lengths (due to the length being the largest cell length in the column), we would like to use your version as a second option next to the current one. Could you make us a suggestion where the user can choose whether the columns should be hug or fill in the GUI? Thank you in advance.

**Comment by mrksoftware** [comment]
Sure!
I have some work to do before I can work again on this, but I'll push a commit asap :+1:

**Comment by mrksoftware** [comment]
@NatashaDudi it should be ok now, please let me know if the caption I've used is clear enough!

**Review by NatashaDudi — APPROVED** [review]
Adds new functionality without interfering with the current features.

**Comment by mrksoftware** [comment]
Great! Is this version already published? I tried to use it but I can't see the new option

**Pull request merged**
